allianceauth/authentication/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from . import views

app_name = 'authentication'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'account/login/',
        TemplateView.as_view(template_name='public/login.html'),
        name='login'
    ),
    path(
        'account/characters/main/',
        views.main_character_change,
        name='change_main_character'
    ),
    path(
        'account/characters/add/',
        views.add_character,
        name='add_character'
    ),
    path(
        'account/tokens/manage/',
        views.token_management,
        name='token_management'
    ),
    path(
        'account/tokens/delete/<int:token_id>',
        views.token_delete,
        name='token_delete'
    ),
    path(
        'account/tokens/refresh/<int:token_id>',
        views.token_refresh,
        name='token_refresh'
    ),
    path('dashboard/', views.dashboard, name='dashboard'),
]

allianceauth/notifications/urls.py
from django.urls import path
from . import views

app_name = 'notifications'
# Notifications
urlpatterns = [
    path('remove_notifications/<int:notif_id>/', views.remove_notification, name='remove'),
    path('notifications/mark_all_read/', views.mark_all_read, name='mark_all_read'),
    path('notifications/delete_all_read/', views.delete_all_read, name='delete_all_read'),
    path('notifications/', views.notification_list, name='list'),
    path('notifications/<int:notif_id>/', views.notification_view, name='view'),
    path(
        'user_notifications_count/<int:user_pk>/',
        views.user_notifications_count,
        name='user_notifications_count'
    ),
]

allianceauth/optimer/urls.py
from django.urls import path

from . import views

app_name = 'optimer'

urlpatterns = [
    path('', views.optimer_view, name='view'),
    path('add/', views.add_optimer_view, name='add'),
    path('<int:optimer_id>/remove/', views.remove_optimer, name='remove'),
    path('<int:optimer_id>/edit/', views.edit_optimer, name='edit'),
]

allianceauth/services/urls.py
from django.conf.urls import include
from allianceauth.hooks import get_hooks
from django.urls import path

from . import views

urlpatterns = [
    # Services
    path('services/', include(([
        path('', views.services_view, name='services'),
        # Tools
        path('tool/fleet_formatter_tool/', views.fleet_formatter_view, name='fleet_format_tool'),
    ], 'services'), namespace='services')),
]

# Append hooked service urls
services = get_hooks('services_hook')
for svc in services:
    urlpatterns += svc().urlpatterns

allianceauth/srp/urls.py
from django.urls import path

from . import views

app_name = 'srp'

urlpatterns = [
    # SRP URLS
    path('', views.srp_management, name='management'),
    path('all/', views.srp_management, {'all': True}, name='all'),
    path('<int:fleet_id>/view/', views.srp_fleet_view, name='fleet'),
    path('add/', views.srp_fleet_add_view, name='add'),
    path('<int:fleet_id>/edit/', views.srp_fleet_edit_view, name='edit'),
    path('<str:fleet_srp>/request/', views.srp_request_view, name='request'),

    # SRP URLS
    path('<int:fleet_id>/remove/', views.srp_fleet_remove, name='remove'),
    path('<int:fleet_id>/disable/', views.srp_fleet_disable, name='disable'),
    path('<int:fleet_id>/enable/', views.srp_fleet_enable, name='enable'),
    path('<int:fleet_id>/complete/', views.srp_fleet_mark_completed,
        name='mark_completed'),
    path('<int:fleet_id>/incomplete/', views.srp_fleet_mark_uncompleted,
        name='mark_uncompleted'),
    path('request/remove/', views.srp_request_remove,
        name="request_remove"),
    path('request/approve/', views.srp_request_approve,
        name='request_approve'),
    path('request/reject/', views.srp_request_reject,
        name='request_reject'),
    path('request/<int:fleet_srp_request_id>/update/', views.srp_request_update_amount,
        name="request_update_amount"),
]

allianceauth/urls.py
from django.urls import path
import esi.urls

from django.conf.urls import include
from django.contrib import admin
from django.views.generic.base import TemplateView

import allianceauth.authentication.views
import allianceauth.authentication.urls
import allianceauth.notifications.urls
import allianceauth.groupmanagement.urls
import allianceauth.services.urls
from allianceauth.authentication.decorators import main_character_required, decorate_url_patterns
from allianceauth import NAME
from allianceauth import views
from allianceauth.authentication import hmac_urls
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    path('i18n/', include('django.conf.urls.i18n')),

    # Authentication
    path('', include(allianceauth.authentication.urls)),
    path('account/login/', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    path('account/', include(hmac_urls)),

    # Admin urls
    path('admin/', admin.site.urls),

    # SSO
    path('sso/', include((esi.urls, 'esi'), namespace='esi')),
    path('sso/login', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    path('', include(allianceauth.notifications.urls)),

    # Groups
    path('', include(allianceauth.groupmanagement.urls)),

    # Services
    path('', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    path('night/', views.NightModeRedirectView.as_view(), name='nightmode')
]


# Append app urls
app_urls = get_hooks('url_hook')
for app in app_urls:
    urlpatterns += [path('', decorate_url_patterns([app().include_pattern], main_character_required))]

allianceauth/analytics/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from uuid import uuid4


class AnalyticsIdentifier(models.Model):

    identifier = models.UUIDField(default=uuid4,
                                editable=False)

    def save(self, *args, **kwargs):
        if not self.pk and AnalyticsIdentifier.objects.exists():
            # Force a single object
            raise ValidationError('There is can be only one \
                                    AnalyticsIdentifier instance')
        self.pk = self.id = 1 # If this happens to be deleted and recreated, force it to be 1
        return super().save(*args, **kwargs)


class AnalyticsPath(models.Model):
    ignore_path = models.CharField(max_length=254, default="/example/", help_text="Regex Expression, If matched no Analytics Page View is sent")


class AnalyticsTokens(models.Model):

    class Analytics_Type(models.TextChoices):
        GA_U = 'GA-U', _('Google Analytics Universal')
        GA_V4 = 'GA-V4', _('Google Analytics V4')

    name = models.CharField(max_length=254)
    type = models.CharField(max_length=254, choices=Analytics_Type.choices)
    token = models.CharField(max_length=254, blank=False)
    send_page_views = models.BooleanField(default=False)
    send_celery_tasks = models.BooleanField(default=False)
    send_stats = models.BooleanField(default=False)
    ignore_paths = models.ManyToManyField(AnalyticsPath, blank=True)

allianceauth/authentication/models.py
import logging

from django.contrib.auth.models import User, Permission
from django.db import models, transaction
from django.utils.translation import gettext_lazy as _
from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo, EveAllianceInfo, EveFactionInfo
from allianceauth.notifications import notify
from django.conf import settings

from .managers import CharacterOwnershipManager, StateManager

logger = logging.getLogger(__name__)


class State(models.Model):
    name = models.CharField(max_length=32, unique=True)
    permissions = models.ManyToManyField(Permission, blank=True)
    priority = models.IntegerField(unique=True, help_text="Users get assigned the state with the highest priority available to them.")

    member_characters = models.ManyToManyField(EveCharacter, blank=True,
                                                help_text="Characters to which this state is available.")
    member_corporations = models.ManyToManyField(EveCorporationInfo, blank=True,
                                                help_text="Corporations to whose members this state is available.")
    member_alliances = models.ManyToManyField(EveAllianceInfo, blank=True,
                                            help_text="Alliances to whose members this state is available.")
    member_factions = models.ManyToManyField(EveFactionInfo, blank=True,
                                            help_text="Factions to whose members this state is available.")
    public = models.BooleanField(default=False, help_text="Make this state available to any character.")

    objects = StateManager()

    class Meta:
        ordering = ['-priority']

    def __str__(self):
        return self.name

    def available_to_character(self, character):
        return self in State.objects.available_to_character(character)

    def available_to_user(self, user):
        return self in State.objects.available_to_user(user)

    def delete(self, **kwargs):
        with transaction.atomic():
            for profile in self.userprofile_set.all():
                profile.assign_state(state=State.objects.exclude(pk=self.pk).get_for_user(profile.user))
        super().delete(**kwargs)


def get_guest_state():
    try:
        return State.objects.get(name='Guest')
    except State.DoesNotExist:
        return State.objects.create(name='Guest', priority=0, public=True)


def get_guest_state_pk():
    return get_guest_state().pk


class UserProfile(models.Model):
    class Meta:
        default_permissions = ('change',)

    user = models.OneToOneField(
        User,
        related_name='profile',
        on_delete=models.CASCADE)
    main_character = models.OneToOneField(
        EveCharacter,
        blank=True,
        null=True,
        on_delete=models.SET_NULL)
    state = models.ForeignKey(
        State,
        on_delete=models.SET_DEFAULT,
        default=get_guest_state_pk)
    LANGUAGE_CHOICES = [
        ('en', _('English')),
        ('de', _('German')),
        ('es', _('Spanish')),
        ('zh-hans', _('Chinese Simplified')),
        ('ru', _('Russian')),
        ('ko', _('Korean')),
        ('fr', _('French')),
        ('ja', _('Japanese')),
        ('it', _('Italian')),
    ]
    language = models.CharField(
        _("Language"), max_length=10,
        choices=LANGUAGE_CHOICES,
        blank=True,
        default='')
    night_mode = models.BooleanField(
        _("Night Mode"),
        blank=True,
        null=True)

    def assign_state(self, state=None, commit=True):
        if not state:
            state = State.objects.get_for_user(self.user)
        if self.state != state:
            self.state = state
            if commit:
                logger.info(f'Updating {self.user} state to {self.state}')
                self.save(update_fields=['state'])
                notify(
                    self.user,
                    _('State changed to: %s' % state),
                    _('Your user\'s state is now: %(state)s')
                    % ({'state': state}),
                    'info'
                )
                from allianceauth.authentication.signals import state_changed

                # We need to ensure we get up to date perms here as they will have just changed.
                # Clear all attribute caches and reload the model that will get passed to the signals!
                self.refresh_from_db()

                state_changed.send(
                    sender=self.__class__, user=self.user, state=self.state
                )

    def __str__(self):
        return str(self.user)
class CharacterOwnership(models.Model):
    class Meta:
        default_permissions = ('change', 'delete')
        ordering = ['user', 'character__character_name']

    character = models.OneToOneField(EveCharacter, on_delete=models.CASCADE, related_name='character_ownership')
    owner_hash = models.CharField(max_length=28, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='character_ownerships')

    objects = CharacterOwnershipManager()

    def __str__(self):
        return f"{self.user}: {self.character}"


class OwnershipRecord(models.Model):
    character = models.ForeignKey(EveCharacter, on_delete=models.CASCADE, related_name='ownership_records')
    owner_hash = models.CharField(max_length=28, db_index=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ownership_records')
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return f"{self.user}: {self.character} on {self.created}"

allianceauth/fleetactivitytracking/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from allianceauth.eveonline.models import EveCharacter


def get_sentinel_user():
    return User.objects.get_or_create(username='deleted')[0]


class Fatlink(models.Model):
    fatdatetime = models.DateTimeField(default=timezone.now)
    duration = models.PositiveIntegerField()
    fleet = models.CharField(max_length=254)
    hash = models.CharField(max_length=254, unique=True)
    creator = models.ForeignKey(User, on_delete=models.SET(get_sentinel_user))

    def __str__(self):
        return self.fleet


class Fat(models.Model):
    character = models.ForeignKey(EveCharacter, on_delete=models.CASCADE)
    fatlink = models.ForeignKey(Fatlink, on_delete=models.CASCADE)
    system = models.CharField(max_length=30)
    shiptype = models.CharField(max_length=100)
    station = models.CharField(max_length=125)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('character', 'fatlink'),)

    def __str__(self):
        return "Fat-link for %s" % self.character.character_name

allianceauth/hrapplications/models.py
from django.contrib.auth.models import User
from django.db import models
from sortedm2m.fields import SortedManyToManyField

from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo

from .managers import ApplicationManager


class ApplicationQuestion(models.Model):
    title = models.CharField(max_length=254, verbose_name='Question')
    help_text = models.CharField(max_length=254, blank=True, null=True)
    multi_select = models.BooleanField(default=False)

    def __str__(self):
        return "Question: " + self.title


class ApplicationChoice(models.Model):
    question = models.ForeignKey(ApplicationQuestion,on_delete=models.CASCADE,related_name="choices")
    choice_text = models.CharField(max_length=200, verbose_name='Choice')

    def __str__(self):
        return self.choice_text


class ApplicationForm(models.Model):
    questions = SortedManyToManyField(ApplicationQuestion)
    corp = models.OneToOneField(EveCorporationInfo, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.corp)


class Application(models.Model):
    form = models.ForeignKey(ApplicationForm, on_delete=models.CASCADE, related_name='applications')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications')
    approved = models.BooleanField(blank=True, null=True, default=None)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    reviewer_character = models.ForeignKey(EveCharacter, on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = ApplicationManager()

    def __str__(self):
        return str(self.user) + " Application To " + str(self.form)

    class Meta:
        permissions = (
            ('approve_application', 'Can approve applications'), ('reject_application', 'Can reject applications'),
            ('view_apis', 'Can view applicant APIs'),)
        unique_together = ('form', 'user')

    @property
    def main_character(self):
        return self.user.profile.main_character

    @property
    def characters(self):
        return [o.character for o in self.user.character_ownerships.all()]

    @property
    def reviewer_str(self):
        if self.reviewer_character:
            return str(self.reviewer_character)
        elif self.reviewer:
            return "User " + str(self.reviewer)
        else:
            return None


class ApplicationResponse(models.Model):
    question = models.ForeignKey(ApplicationQuestion, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='responses')
    answer = models.TextField()

    def __str__(self):
        return str(self.application) + " Answer To " + str(self.question)

    class Meta:
        unique_together = ('question', 'application')


class ApplicationComment(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " comment on " + str(self.application)

allianceauth/permissions_tool/models.py
from django.db import models


class PermissionsTool(models.Model):
    """
    Dummy model for holding permissions
    """
    class Meta:
        managed = False
        permissions = (
            ('audit_permissions', 'Can audit permissions'),
        )

allianceauth/templates/allianceauth/base.html
{% load i18n %}
{% load navactive %}
{% load auth_notifications %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
        {% include 'allianceauth/icons.html' %}

        <title>{% block title %}{% block page_title %}{% endblock page_title %} - {{ SITE_NAME }}{% endblock title %}</title>

        {% include 'bundles/bootstrap-css.html' %}
        {% include 'bundles/fontawesome.html' %}
        {% include 'bundles/auth-base-css.html' %}

        {% block extra_css %}{% endblock extra_css %}
    </head>

    <body class="{% if NIGHT_MODE %}template-dark-mode{% else %}template-light-mode{% endif %}">
        {% if user.is_authenticated %}
            <div id="wrapper" class="container">
                <!-- Navigation -->
                {% include 'allianceauth/top-menu.html' %}
                <div class="row" id="site-body-wrapper">
                    {% include 'allianceauth/side-menu.html' %}
                    <div class="col-sm-10">
                        {% include 'allianceauth/messages.html' %}
                        {% block content %}
                        {% endblock content %}
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        {% endif %}

        {% include 'bundles/bootstrap-js.html' %}
        {% include 'bundles/jquery-visibility-js.html' %}

        <script>
            let notificationUPdateSettings = {
                notificationsListViewUrl: "{% url 'notifications:list' %}",
                notificationsRefreshTime: "{% notifications_refresh_time %}",
                userNotificationsCountViewUrl: "{% url 'notifications:user_notifications_count' request.user.pk %}"
            };
        </script>
        {% include 'bundles/refresh-notifications-js.html' %}
        {% include 'bundles/evetime-js.html' %}

        {% block extra_javascript %}
        {% endblock extra_javascript %}
        <script>
            {% block extra_script %}
            {% endblock extra_script %}
        </script>
    </body>
</html>

allianceauth/templates/allianceauth/icons.html
{% load static %}
<link rel="icon" type="image/png" href="{% static 'allianceauth/icons/favicon-16x16.png' %}" sizes="16x16">
<link rel="icon" type="image/png" href="{% static 'allianceauth/icons/favicon-32x32.png' %}" sizes="32x32">
<link rel="icon" type="image/png" href="{% static 'allianceauth/icons/favicon-96x96.png' %}" sizes="96x96">
<link rel="apple-touch-icon" href="{% static 'allianceauth/icons/apple-touch-icon.png' %}">

allianceauth/templates/allianceauth/messages.html
{% if messages %}
    <br>
    {% for message in messages %}
        <div class="alert alert-{{ message.level_tag }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>

            <div class="message-icon pull-left" style="margin-right: 0.5rem;">
                {% if message.level_tag == "info" %}
                    <i class="fas fa-info-circle"></i>
                {% elif message.level_tag == "success" %}
                    <i class="fas fa-check-circle"></i>
                {% elif message.level_tag == "warning" %}
                    <i class="fas fa-exclamation-circle"></i>
                {% elif "danger" in message.level_tag %}
                    <i class="fas fa-exclamation-triangle"></i>
                {% endif %}
            </div>

            <div class="message-text" style="margin-left: 2.5rem;">
                {{ message }}
            </div>
        </div>
    {% endfor %}
{% endif %}

allianceauth/templates/allianceauth/night-toggle.html
{% load i18n %}

<li>
    <a href="{% url 'nightmode' %}?next={{ request.path|urlencode }}">
        <i class="fas {% if NIGHT_MODE %}fa-toggle-on{% else %}fa-toggle-off{% endif %}" aria-hidden="true"></i>
        {% translate "Night Mode" %}
    </a>
</li>

allianceauth/templates/allianceauth/notifications_menu_item.html
{% load i18n %}
{% load auth_notifications %}

{% with unread_count=request.user|user_unread_notification_count %}
    {% if unread_count > 0 %}
        <a href="{% url 'notifications:list' %}">{% translate "Notifications" %}
            <span class="badge">{{ unread_count }}</span>
        </a>
    {% else %}
        <a href="{% url 'notifications:list' %}">
            <i class="far fa-bell"></i>
        </a>
    {% endif %}
{% endwith %}

allianceauth/templates/allianceauth/side-menu.html
{% load i18n %}
{% load navactive %}
{% load menu_items %}

<div class="col-sm-2 auth-side-navbar" role="navigation">
    <div class="collapse navbar-collapse auth-menus-collapse auth-side-navbar-collapse">
        <ul class="nav nav-pills nav-stacked gray-icon-color" id="side-menu">
            <li>
                <a class="{% navactive request 'authentication:dashboard' %}" href="{% url 'authentication:dashboard' %}">
                    <i class="fas fa-tachometer-alt fa-fw"></i> {% translate "Dashboard" %}
                </a>
            </li>
            <li>
                <a class="{% navactive request 'groupmanagement:groups' %}" href="{% url 'groupmanagement:groups' %}">
                    <i class="fas fa-users fa-fw"></i> {% translate "Groups" %}
                </a>
            </li>

            {% menu_items %}
        </ul>
    </div>
</div>

allianceauth/templates/allianceauth/top-menu-admin.html
{% load i18n %}


{% if user.is_authenticated %}
    {% if user.is_staff %}
        <li role="separator" class="divider"></li>
        <li><a href="{% url 'admin:index' %}" target="_blank" rel="noopener noreferer">
            <i class="fas fa-user-shield"></i>
            {% translate "Admin" %}</a>
        </li>
    {% endif %}
{% endif %}

{% if user.is_superuser %}
    <li role="separator" class="divider"></li>
    <li>
        <a href="https://allianceauth.readthedocs.io/" target="_blank" rel="noopener noreferer">
            <i class="fas fa-question-circle fa-fw"></i>
            {% translate "AA Documentation" %}
        </a>
    </li>

    <li>
        <a href="https://discord.gg/fjnHAmk" target="_blank" rel="noopener noreferer">
            <i class="fab fa-discord fa-fw"></i>
            {% translate "AA Support Discord" %}
        </a>
    </li>
{% endif %}

allianceauth/templates/allianceauth/top-menu-user-dropdown.html
{% load i18n %}
{% load evelinks %}

<li class="top-user-menu dropdown{% if request.user.profile.main_character %} with-main-character{% endif %}">
    <a href="#" class="dropdown-toggle" type="button" id="top-user-menu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
        {% if request.user.profile.main_character %}
            {% with request.user.profile.main_character as main %}
                <img class="img-rounded ra-avatar" src="{{ main.character_id|character_portrait_url:32 }}" alt="{{ main.character_name }}">
                <span class="hidden-sm hidden-md hidden-lg">
                    {{ main.character_name }} - {% translate "User Menu" %}
                </span>
            {% endwith %}
        {% else %}
            {% translate "User Menu" %}
        {% endif %}
        <span class="caret"></span>
    </a>

    <ul class="dropdown-menu top-user-menu" aria-labelledby="top-user-menu">
        <!-- user avatar -->
        {% if request.user.profile.main_character %}
            <li>
                {% with request.user.profile.main_character as main %}
                    <p class="text-center">
                        <img class="img-rounded ra-avatar" src="{{ main.character_id|character_portrait_url:256 }}" alt="{{ main.character_name }}">
                    </p>

                    <p class="text-center">
                        <span style="display: block;">{{ main.character_name }}</span>
                        <span style="display: block;">{{ main.corporation_name }}</span>

                        {% if main.alliance_name %}
                            <span style="display: block;">{{ main.alliance_name }}</span>
                        {% endif %}
                    </p>
                {% endwith %}
            </li>
            <li role="separator" class="divider"></li>
        {% endif %}

        <li class="top-menu-bar-language-select">
            {% include 'public/lang_select.html' %}
        </li>

        <li role="separator" class="divider"></li>

        <!-- night mode toggle -->
        {% include 'allianceauth/night-toggle.html' %}

        <!-- admin related menu items -->
        {% include 'allianceauth/top-menu-admin.html' %}

        <!-- logout / login -->
        <li role="separator" class="divider"></li>
        {% if user.is_authenticated %}
            <li>
                <a href="{% url 'authentication:token_management' %}">
                    <i class="fas fa-user-lock"></i>
                    {% translate "Token Management" %}
                </a>
            </li>
            <li role="separator" class="divider"></li>

            <li><a href="{% url 'logout' %}">{% translate "Logout" %}</a></li>
        {% else %}
            <li><a href="{% url 'authentication:login' %}">{% translate "Login" %}</a></li>
        {% endif %}
    </ul>
</li>

allianceauth/templates/allianceauth/top-menu.html
{% load i18n %}
{% load static %}
{% load navactive %}
<nav class="navbar navbar-default navbar-static-top auth-navbar-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".auth-menus-collapse">
                <span class="sr-only">{% translate "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a class="navbar-brand">
                <img src="{% static 'allianceauth/icons/favicon-32x32.png' %}" style="display: inline-block;" height="32" width="32" alt="{{ SITE_NAME }}"/>
                {{ SITE_NAME }}
            </a>
        </div>

        <div class="collapse navbar-collapse auth-menus-collapse">
            <ul class="nav navbar-nav navbar-right navbar-pills">
                <li class="nav-item-eve-time">
                    <div class="eve-time-wrapper">{% translate "Eve Time" %}: <span class="eve-time-clock"></span></div>
                </li>
                <li class="{% navactive request 'notifications:' %}" id="menu_item_notifications">
                    {% include 'allianceauth/notifications_menu_item.html' %}
                </li>

                {% include 'allianceauth/top-menu-user-dropdown.html' %}
            </ul>
        </div>
    </div>
</nav>